---
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sarajevo
    volumes:
      - /mnt/ssd/docker/jellyfin/config:/config
      - /mnt/ssd/media/tv:/data/tvshows
      - /mnt/ssd/media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
